import "./globals.css";

export const metadata = {
  title: "Sabrineh Nextjs CoffeeShop",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" dir="rtl" suppressHydrationWarning={true}>
      <body>{children}</body>
    </html>
  );
}
